/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef DONORS_GEN_H
#define DONORS_GEN_H
const char *const DONORS_PATRONS[] = {
	"Khronos\302\256 Group <https://www.khronos.org/>",
	"OSS Capital <https://oss.capital/>",
	0
};
const char *const DONORS_SPONSORS_PLATINUM[] = {
	"Scorewarrior <https://scwr.gg/godot>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com/>",
	0
};
const char *const DONORS_SPONSORS_GOLD[] = {
	"Mega Crit <https://www.megacrit.com/>",
	"Prehensile Tales <https://prehensile-tales.com>",
	"Robot Gentleman <http://robotgentleman.com/>",
	0
};
const char *const DONORS_SPONSORS_SILVER[] = {
	"Bippinbits <https://bippinbits.com/>",
	"Broken Rules <https://brokenrul.es>",
	"Chasing Carrots <https://www.chasing-carrots.com>",
	"Copia Wealth Studios <https://copiawealthstudios.com/>",
	"LoadComplete <https://loadcomplete.com/>",
	"Null <https://null.com/>",
	"Orbital Knight <https://www.orbitalknight.com/>",
	"Playful Studios <https://playfulstudios.com/>",
	"Re-Logic <https://re-logic.com/>",
	0
};
const char *const DONORS_MEMBERS_DIAMOND[] = {
	"ASIFA-Hollywood <https://www.asifa-hollywood.org/>",
	"Christina Coffin <https://bsky.app/profile/christinacoffin.bsky.social>",
	"Dominic Harris <https://wayfarer-games.com/>",
	"Kiri \042ExpiredPopsicle\042 Artemis <https://expiredpopsicle.com/>",
	"Petr Kharitonov <https://petrkharitonov.com/>",
	"Seats.aero <https://seats.aero/>",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype>",
	"And 5 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_TITANIUM[] = {
	"Adriaan de Jongh <https://adriaan.games>",
	"Basically Games",
	"Draknek & Friends <https://www.draknek.org/>",
	"Garry Newman",
	"Gigabrain AI Reddit Search Engine <https://thegigabrain.com/?utm_source=godot>",
	"Jettelly <https://jettelly.com/>",
	"Justo Delgado Baud\303\255 <https://portfolio.mrcdk.com/>",
	"Kenney <https://kenney.nl/>",
	"Lucid Silence Games",
	"Matthew Hall <https://crossyroad.com/>",
	"PolyMars <https://polymars.dev/>",
	"Purple Moss Collectors <https://purplemosscollectors.com/>",
	"RPG in a Box <https://www.rpginabox.com>",
	"Starkandco <https://github.com/Starkandco>",
	"Studio Sunshower <https://www.studiosunshower.com/>",
	"TrampolineTales <https://TrampolineTales.com/>",
	"\347\262\237\344\272\214\345\215\216 (Su Erhua)",
	"And 4 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_PLATINUM[] = {
	"Andy Touch",
	"BlockImperiumGames (BIG)",
	"Bytten Studio",
	"Christopher Shifflett",
	"Cody Bentley",
	"Darrin Massena",
	"Fabio Alessandrelli",
	"HP van Braam",
	"iCommitGames",
	"Jason Hamilton",
	"Jonah Stich",
	"Josh Anthony",
	"Ludvig Temperli Risan",
	"Matthew Ekenstedt",
	"Memories in 8Bit",
	"Michael Martin",
	"Mike King",
	"Neal Gompa (Conan Kudo)",
	"Nico Ulriksen",
	"Nikita Blizniuk",
	"Raptor85",
	"R\303\251mi Verschelde",
	"Ronnie Cheng",
	"Ryan Heath",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"Stephan Kessler",
	"Stephen Rice",
	"And 14 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_GOLD[] = {
	"2 Nerdy Nerds",
	"73unny",
	"80px",
	"Abigail F.",
	"Admiral Potato",
	"afreytes",
	"AinaVT",
	"Ajat BlackSun",
	"Alex177Alex",
	"alMoo Games",
	"Alva Majo",
	"Andrew Eiche",
	"Antti Vesanen",
	"Arediss",
	"Asher Glick",
	"Axthelm",
	"BangTheWall",
	"Benito",
	"Benjamin Bridges",
	"Ben Rog-Wilhelm",
	"BetaTester704",
	"Brut",
	"Bryce Dixon",
	"Carlo Cabanilla",
	"Carlo del Mundo",
	"Carl van der Geest",
	"Chocolate Software",
	"Chris Backas",
	"Chris Lambson",
	"Christine Elisabeth Koppel",
	"Cindy Trieu",
	"ClarkThyLord",
	"Codex404",
	"cora",
	"Daniel Eichler",
	"Daniel Krafft",
	"Datzju",
	"David Chen Zhen",
	"David Coles",
	"David Hubber",
	"David Snopek",
	"Deakcor",
	"Delton Ding",
	"dgehrig",
	"Disco Cat",
	"Distorted Realities",
	"DitherDream",
	"Dominik Frizel",
	"Don't You Know Who I Am? Inc.",
	"Dustuu",
	"Dylan Dromard",
	"Edelweiss",
	"eelSkillz",
	"Emily Flion",
	"Ends",
	"Eren Ogrul",
	"Eric Brand",
	"Eric Phy",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"Fanny Pack Studios",
	"Felix Adam",
	"FeralBytes",
	"Francisco Aliaga",
	"Francis Jasmin",
	"Frozen Fractal",
	"Gaudipern",
	"GetIntoGameDev",
	"GlassBrick",
	"Grau",
	"Grzegorz Wereszko",
	"Guangzhou Lingchan",
	"Guilherme Cattani",
	"Hayden Oliver",
	"hiulit",
	"https://domi.zip",
	"Huedeane",
	"Ikuti",
	"Illyan",
	"I.M.I.Self",
	"Immaculate Lift Studio",
	"Intrepid Marmot LLC",
	"Isaac Marovitz",
	"Ivan Tabashki",
	"jakemiki",
	"Jam",
	"Jason Cawood",
	"Jeff Hungerford",
	"Jes\303\272s Chicharro",
	"Johannes Wuensch",
	"John Gabriel",
	"Jonas Yamazaki",
	"Jonathan",
	"Jos\303\251 Canepa",
	"Julian Todd",
	"Justin Laster",
	"Justin Sasso",
	"Kalydi Bal\303\241zs",
	"KAR Games",
	"Kiryonn",
	"kodebold",
	"KOGA Mitsuhiro (@shiena)",
	"korinVR",
	"Kristian Kriehl",
	"KyletheDab",
	"Lars Thie\303\237en",
	"Lisandro Lorea (Red Mage Games)",
	"Logan Apple",
	"Luca Junge",
	"LyaaaaaGames",
	"m1n1ster",
	"Madison Nicole Videogames",
	"Mara Huldra",
	"Marek Belski",
	"Martin \305\240enke\305\231\303\255k",
	"Matthias B.",
	"Michael Alexsander",
	"Michael Gooch",
	"Michael Harrington",
	"Modus Ponens",
	"Moshe Harris",
	"Moth Soup",
	"Mr. Byte",
	"Muscarian Softworks",
	"Nassor Paulino da Silva",
	"Neuroticfly Games",
	"nezticle",
	"nikkehtine",
	"Niklas Wahrman",
	"Nitzan Bueno",
	"NotNet",
	"Oathbringer",
	"Officine Pixel",
	"ohanaya3",
	"Okatima AB",
	"Oscar Robin",
	"ovym",
	"Patrick Traynor",
	"P\303\251ter Horv\303\241th-L\303\241z\303\241r",
	"Petr Mal\303\241\304\215",
	"pirey",
	"protogames",
	"Rafa Laguna",
	"Reid Hannaford",
	"@reilaos",
	"Request",
	"re:thinc",
	"Richard Iv\303\241nek",
	"Robin Ward",
	"Ronny M\303\274hle",
	"Rub\303\251n R\303\274ger",
	"Samuel Judd",
	"Santi_FC",
	"Seref Karahan",
	"shazzner",
	"Shiny Shinken",
	"Silverclad Studios",
	"Skie Radscale",
	"Snow Diamond",
	"Sofox",
	"Space Kraken Studios",
	"Spoony Panda",
	"tenuki",
	"ThatGamer",
	"Thomas Lobig",
	"Tobias Bocanegra",
	"Tom Langwaldt",
	"Trevor Slocum",
	"tukon",
	"twitch.tv/RobitussinMD",
	"Tyler C",
	"Urban Protagonist",
	"Vincent Foulon",
	"Vojtech Lacina",
	"Voxel Floof",
	"Watchinofoye",
	"Yannick",
	"zikes",
	"Zoey Smith",
	"\345\227\257\345\244\247\347\210\267",
	"And 143 anonymous donors",
	0
};
#endif // DONORS_GEN_H
